import { useRef } from "react";
import style from "./Hero.module.scss";
import TiltImage from "./tilt-image/TiltImage";
import { Check, Video } from "lucide-react";
import { useNavigate } from "react-router-dom";
import Button from "../common/button/Button";
const Hero = () => {
  const ref = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();

  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    const rect = ref.current!.getBoundingClientRect();

    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    const centerX = rect.width / 2;
    const centerY = rect.height / 2;

    const rotateX = ((y - centerY) / (rect.height / 2)) * -3;
    const rotateY = ((x - centerX) / (rect.width / 2)) * 3;

    ref.current!.style.transform = `rotateX(${rotateX}deg) rotateY(${rotateY}deg)`;
  };
  const handleMouseLeave = () => {
    ref.current!.style.transform = "rotateX(0deg) rotateY(0deg)";
  };

  const specialSkills = [
    "No design skills needed",
    "Fast generation",
    "High CTR templates",
  ];

  return (
    <section className={style.heroSection}>
      <div className={style.heroTitle}>
        AI Thumbnail Generator for your{" "}
        <span className={style.highlight}>Videos.</span>
      </div>
      <div className={style.heroSubtitle}>
        Stop wasting time on designing thumbnails. Get high-converting
        thumbnails generated by AI in seconds with your advanced AI.
      </div>
      <div className={style.heroActions}>
        <Button
          text="Generate Now"
          variant="contained"
          handleClick={() => navigate("/generate")}
          rounded
        />
        <Button
          text="See How It Works"
          variant="outlined"
          handleClick={() => navigate("/generate")}
          startIcon={Video}
          rounded
        />
      </div>
      <div className={style.heroFeatures}>
        {specialSkills.map((skill, index) => (
          <p key={index} className={style.feature}>
            <span className={style.tickMark}>
              <Check />
            </span>
            <span>{skill}</span>
          </p>
        ))}
      </div>
      <div className={style.tiltWrapper}>
        <div
          className={style.tiltInner}
          ref={ref}
          onMouseMove={handleMouseMove}
          onMouseLeave={handleMouseLeave}
        >
          <TiltImage />
        </div>
      </div>
    </section>
  );
};

export default Hero;
